name: budgetapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.0.5+1
  get:
  google_fonts: ^2.3.1
  email_validator: ^2.0.1
  intl: ^0.17.0
  animated_bottom_navigation_bar: ^0.3.2
  circular_menu: ^1.2.3
  syncfusion_flutter_charts: ^20.1.50
  flutter_easyloading: 
  get_storage:
  #firebase
  cloud_functions: 
  firebase_auth: 
  paginate_firestore: 
  # awesome_notifications: ^0.0.6+11
  firebase_database: 
  firebase_core: 
  firebase_analytics: 
  firebase_storage: ^10.2.5
  flutter_phoenix: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
